### ISSUE TITLE
非常棒

### ISSUE THREAD

**Issue by yinxulai** [AlexanderRong/Unity3D-Official-Documents-5.3.4f1-Translation-For-Chinese#1]
刚开始接触Unity3D 非常感谢你的文档  虽然说我还没有开始看  因为我是mac系统 好像不能直接安装 但是我仍然觉得很好   非常感谢

**Comment by AlexanderRong** [comment]
多谢你的肯定。
你下载 Unity 时候附带下载的文档，我就是用那个附带文档本地翻译的。
你把项目下载下来后，直接找到 index 网页打开就好了，里面的链接我都没改的。
若有疑问或问题，随时欢迎交流，大家共同进步！
